#!/bin/bash
wget https://www.minlplib.org/nl/alan.nl
wget https://www.minlplib.org/nl/ball_mk2_10.nl
wget https://www.minlplib.org/nl/ball_mk2_30.nl
wget https://www.minlplib.org/nl/ball_mk3_10.nl
wget https://www.minlplib.org/nl/ball_mk3_20.nl
wget https://www.minlplib.org/nl/ball_mk3_30.nl
wget https://www.minlplib.org/nl/ball_mk4_05.nl
wget https://www.minlplib.org/nl/ball_mk4_10.nl
wget https://www.minlplib.org/nl/ball_mk4_15.nl
wget https://www.minlplib.org/nl/batch.nl
wget https://www.minlplib.org/nl/batch0812.nl
wget https://www.minlplib.org/nl/batchdes.nl
wget https://www.minlplib.org/nl/batchs101006m.nl
wget https://www.minlplib.org/nl/batchs121208m.nl
wget https://www.minlplib.org/nl/batchs151208m.nl
wget https://www.minlplib.org/nl/batchs201210m.nl
wget https://www.minlplib.org/nl/clay0203hfsg.nl
wget https://www.minlplib.org/nl/clay0203m.nl
wget https://www.minlplib.org/nl/clay0204hfsg.nl
wget https://www.minlplib.org/nl/clay0204m.nl
wget https://www.minlplib.org/nl/clay0205hfsg.nl
wget https://www.minlplib.org/nl/clay0205m.nl
wget https://www.minlplib.org/nl/clay0303hfsg.nl
wget https://www.minlplib.org/nl/clay0303m.nl
wget https://www.minlplib.org/nl/clay0304hfsg.nl
wget https://www.minlplib.org/nl/clay0304m.nl
wget https://www.minlplib.org/nl/clay0305hfsg.nl
wget https://www.minlplib.org/nl/clay0305m.nl
wget https://www.minlplib.org/nl/color_lab2_4x0.nl
wget https://www.minlplib.org/nl/color_lab6b_4x20.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon20.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon20r.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon30.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon30r.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon40.nl
wget https://www.minlplib.org/nl/cvxnonsep_normcon40r.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig20.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig20r.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig30.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig30r.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig40.nl
wget https://www.minlplib.org/nl/cvxnonsep_nsig40r.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon20.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon20r.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon30.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon30r.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon40.nl
wget https://www.minlplib.org/nl/cvxnonsep_pcon40r.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig20.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig20r.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig30.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig30r.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig40.nl
wget https://www.minlplib.org/nl/cvxnonsep_psig40r.nl
wget https://www.minlplib.org/nl/du-opt.nl
wget https://www.minlplib.org/nl/du-opt5.nl
wget https://www.minlplib.org/nl/enpro48pb.nl
wget https://www.minlplib.org/nl/enpro56pb.nl
wget https://www.minlplib.org/nl/ex1223.nl
wget https://www.minlplib.org/nl/ex1223a.nl
wget https://www.minlplib.org/nl/ex1223b.nl
wget https://www.minlplib.org/nl/ex4.nl
wget https://www.minlplib.org/nl/fac1.nl
wget https://www.minlplib.org/nl/fac2.nl
wget https://www.minlplib.org/nl/fac3.nl
wget https://www.minlplib.org/nl/flay02h.nl
wget https://www.minlplib.org/nl/flay02m.nl
wget https://www.minlplib.org/nl/flay03h.nl
wget https://www.minlplib.org/nl/flay03m.nl
wget https://www.minlplib.org/nl/flay04h.nl
wget https://www.minlplib.org/nl/flay04m.nl
wget https://www.minlplib.org/nl/flay05h.nl
wget https://www.minlplib.org/nl/flay05m.nl
wget https://www.minlplib.org/nl/flay06h.nl
wget https://www.minlplib.org/nl/flay06m.nl
wget https://www.minlplib.org/nl/fo7.nl
wget https://www.minlplib.org/nl/fo7_2.nl
wget https://www.minlplib.org/nl/fo7_ar25_1.nl
wget https://www.minlplib.org/nl/fo7_ar2_1.nl
wget https://www.minlplib.org/nl/fo7_ar3_1.nl
wget https://www.minlplib.org/nl/fo7_ar4_1.nl
wget https://www.minlplib.org/nl/fo7_ar5_1.nl
wget https://www.minlplib.org/nl/fo8.nl
wget https://www.minlplib.org/nl/fo8_ar25_1.nl
wget https://www.minlplib.org/nl/fo8_ar2_1.nl
wget https://www.minlplib.org/nl/fo8_ar3_1.nl
wget https://www.minlplib.org/nl/fo8_ar4_1.nl
wget https://www.minlplib.org/nl/fo8_ar5_1.nl
wget https://www.minlplib.org/nl/fo9.nl
wget https://www.minlplib.org/nl/fo9_ar25_1.nl
wget https://www.minlplib.org/nl/fo9_ar2_1.nl
wget https://www.minlplib.org/nl/fo9_ar3_1.nl
wget https://www.minlplib.org/nl/fo9_ar4_1.nl
wget https://www.minlplib.org/nl/fo9_ar5_1.nl
wget https://www.minlplib.org/nl/gams01.nl
wget https://www.minlplib.org/nl/gbd.nl
wget https://www.minlplib.org/nl/hybriddynamic_fixed.nl
wget https://www.minlplib.org/nl/ibs2.nl
wget https://www.minlplib.org/nl/jit1.nl
wget https://www.minlplib.org/nl/m3.nl
wget https://www.minlplib.org/nl/m6.nl
wget https://www.minlplib.org/nl/m7.nl
wget https://www.minlplib.org/nl/m7_ar25_1.nl
wget https://www.minlplib.org/nl/m7_ar2_1.nl
wget https://www.minlplib.org/nl/m7_ar3_1.nl
wget https://www.minlplib.org/nl/m7_ar4_1.nl
wget https://www.minlplib.org/nl/m7_ar5_1.nl
wget https://www.minlplib.org/nl/meanvar-orl400_05_e_8.nl
wget https://www.minlplib.org/nl/meanvarx.nl
wget https://www.minlplib.org/nl/netmod_dol1.nl
wget https://www.minlplib.org/nl/netmod_dol2.nl
wget https://www.minlplib.org/nl/netmod_kar1.nl
wget https://www.minlplib.org/nl/netmod_kar2.nl
wget https://www.minlplib.org/nl/no7_ar25_1.nl
wget https://www.minlplib.org/nl/no7_ar2_1.nl
wget https://www.minlplib.org/nl/no7_ar3_1.nl
wget https://www.minlplib.org/nl/no7_ar4_1.nl
wget https://www.minlplib.org/nl/no7_ar5_1.nl
wget https://www.minlplib.org/nl/nvs03.nl
wget https://www.minlplib.org/nl/nvs10.nl
wget https://www.minlplib.org/nl/nvs11.nl
wget https://www.minlplib.org/nl/nvs12.nl
wget https://www.minlplib.org/nl/nvs15.nl
wget https://www.minlplib.org/nl/o7.nl
wget https://www.minlplib.org/nl/o7_2.nl
wget https://www.minlplib.org/nl/o7_ar25_1.nl
wget https://www.minlplib.org/nl/o7_ar2_1.nl
wget https://www.minlplib.org/nl/o7_ar3_1.nl
wget https://www.minlplib.org/nl/o7_ar4_1.nl
wget https://www.minlplib.org/nl/o7_ar5_1.nl
wget https://www.minlplib.org/nl/o8_ar4_1.nl
wget https://www.minlplib.org/nl/o9_ar4_1.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_3d_h.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_3d_m.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_4d_h.nl
wget https://www.minlplib.org/nl/p_ball_10b_5p_4d_m.nl
wget https://www.minlplib.org/nl/p_ball_10b_7p_3d_h.nl
wget https://www.minlplib.org/nl/p_ball_10b_7p_3d_m.nl
wget https://www.minlplib.org/nl/p_ball_15b_5p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_15b_5p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_20b_5p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_20b_5p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_20b_5p_3d_h.nl
wget https://www.minlplib.org/nl/p_ball_20b_5p_3d_m.nl
wget https://www.minlplib.org/nl/p_ball_30b_10p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_30b_10p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_30b_5p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_30b_5p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_30b_5p_3d_h.nl
wget https://www.minlplib.org/nl/p_ball_30b_5p_3d_m.nl
wget https://www.minlplib.org/nl/p_ball_30b_7p_2d_h.nl
wget https://www.minlplib.org/nl/p_ball_30b_7p_2d_m.nl
wget https://www.minlplib.org/nl/p_ball_40b_5p_3d_h.nl
wget https://www.minlplib.org/nl/p_ball_40b_5p_3d_m.nl
wget https://www.minlplib.org/nl/p_ball_40b_5p_4d_h.nl
wget https://www.minlplib.org/nl/p_ball_40b_5p_4d_m.nl
wget https://www.minlplib.org/nl/pedigree_ex1058.nl
wget https://www.minlplib.org/nl/pedigree_ex485.nl
wget https://www.minlplib.org/nl/pedigree_ex485_2.nl
wget https://www.minlplib.org/nl/pedigree_sim2000.nl
wget https://www.minlplib.org/nl/pedigree_sim400.nl
wget https://www.minlplib.org/nl/pedigree_sp_top4_250.nl
wget https://www.minlplib.org/nl/pedigree_sp_top4_300.nl
wget https://www.minlplib.org/nl/pedigree_sp_top4_350tr.nl
wget https://www.minlplib.org/nl/pedigree_sp_top5_200.nl
wget https://www.minlplib.org/nl/pedigree_sp_top5_250.nl
wget https://www.minlplib.org/nl/portfol_buyin.nl
wget https://www.minlplib.org/nl/portfol_card.nl
wget https://www.minlplib.org/nl/portfol_classical050_1.nl
wget https://www.minlplib.org/nl/portfol_classical200_2.nl
wget https://www.minlplib.org/nl/portfol_roundlot.nl
wget https://www.minlplib.org/nl/procurement2mot.nl
wget https://www.minlplib.org/nl/ravempb.nl
wget https://www.minlplib.org/nl/risk2bpb.nl
wget https://www.minlplib.org/nl/rsyn0805hfsg.nl
wget https://www.minlplib.org/nl/rsyn0805m.nl
wget https://www.minlplib.org/nl/rsyn0805m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0805m02m.nl
wget https://www.minlplib.org/nl/rsyn0805m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0805m03m.nl
wget https://www.minlplib.org/nl/rsyn0805m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0805m04m.nl
wget https://www.minlplib.org/nl/rsyn0810hfsg.nl
wget https://www.minlplib.org/nl/rsyn0810m.nl
wget https://www.minlplib.org/nl/rsyn0810m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0810m02m.nl
wget https://www.minlplib.org/nl/rsyn0810m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0810m03m.nl
wget https://www.minlplib.org/nl/rsyn0810m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0810m04m.nl
wget https://www.minlplib.org/nl/rsyn0815hfsg.nl
wget https://www.minlplib.org/nl/rsyn0815m.nl
wget https://www.minlplib.org/nl/rsyn0815m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0815m02m.nl
wget https://www.minlplib.org/nl/rsyn0815m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0815m03m.nl
wget https://www.minlplib.org/nl/rsyn0815m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0815m04m.nl
wget https://www.minlplib.org/nl/rsyn0820hfsg.nl
wget https://www.minlplib.org/nl/rsyn0820m.nl
wget https://www.minlplib.org/nl/rsyn0820m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0820m02m.nl
wget https://www.minlplib.org/nl/rsyn0820m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0820m03m.nl
wget https://www.minlplib.org/nl/rsyn0820m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0820m04m.nl
wget https://www.minlplib.org/nl/rsyn0830hfsg.nl
wget https://www.minlplib.org/nl/rsyn0830m.nl
wget https://www.minlplib.org/nl/rsyn0830m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0830m02m.nl
wget https://www.minlplib.org/nl/rsyn0830m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0830m03m.nl
wget https://www.minlplib.org/nl/rsyn0830m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0830m04m.nl
wget https://www.minlplib.org/nl/rsyn0840hfsg.nl
wget https://www.minlplib.org/nl/rsyn0840m.nl
wget https://www.minlplib.org/nl/rsyn0840m02hfsg.nl
wget https://www.minlplib.org/nl/rsyn0840m02m.nl
wget https://www.minlplib.org/nl/rsyn0840m03hfsg.nl
wget https://www.minlplib.org/nl/rsyn0840m03m.nl
wget https://www.minlplib.org/nl/rsyn0840m04hfsg.nl
wget https://www.minlplib.org/nl/rsyn0840m04m.nl
wget https://www.minlplib.org/nl/slay04h.nl
wget https://www.minlplib.org/nl/slay04m.nl
wget https://www.minlplib.org/nl/slay05h.nl
wget https://www.minlplib.org/nl/slay05m.nl
wget https://www.minlplib.org/nl/slay06h.nl
wget https://www.minlplib.org/nl/slay06m.nl
wget https://www.minlplib.org/nl/slay07h.nl
wget https://www.minlplib.org/nl/slay07m.nl
wget https://www.minlplib.org/nl/slay08h.nl
wget https://www.minlplib.org/nl/slay08m.nl
wget https://www.minlplib.org/nl/slay09h.nl
wget https://www.minlplib.org/nl/slay09m.nl
wget https://www.minlplib.org/nl/slay10h.nl
wget https://www.minlplib.org/nl/slay10m.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b010-011.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b020-022.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b050-055.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b100-110.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b150-165.nl
wget https://www.minlplib.org/nl/smallinvDAXr1b200-220.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b010-011.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b020-022.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b050-055.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b100-110.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b150-165.nl
wget https://www.minlplib.org/nl/smallinvDAXr2b200-220.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b010-011.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b020-022.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b050-055.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b100-110.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b150-165.nl
wget https://www.minlplib.org/nl/smallinvDAXr3b200-220.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b010-011.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b020-022.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b050-055.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b100-110.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b150-165.nl
wget https://www.minlplib.org/nl/smallinvDAXr4b200-220.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b010-011.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b020-022.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b050-055.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b100-110.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b150-165.nl
wget https://www.minlplib.org/nl/smallinvDAXr5b200-220.nl
wget https://www.minlplib.org/nl/squfl010-025.nl
wget https://www.minlplib.org/nl/squfl010-040.nl
wget https://www.minlplib.org/nl/squfl010-080.nl
wget https://www.minlplib.org/nl/squfl015-060.nl
wget https://www.minlplib.org/nl/squfl015-080.nl
wget https://www.minlplib.org/nl/squfl020-040.nl
wget https://www.minlplib.org/nl/squfl020-050.nl
wget https://www.minlplib.org/nl/squfl020-150.nl
wget https://www.minlplib.org/nl/squfl025-025.nl
wget https://www.minlplib.org/nl/squfl025-030.nl
wget https://www.minlplib.org/nl/squfl025-040.nl
wget https://www.minlplib.org/nl/squfl030-100.nl
wget https://www.minlplib.org/nl/squfl030-150.nl
wget https://www.minlplib.org/nl/squfl040-080.nl
wget https://www.minlplib.org/nl/sssd08-04.nl
wget https://www.minlplib.org/nl/sssd12-05.nl
wget https://www.minlplib.org/nl/sssd15-04.nl
wget https://www.minlplib.org/nl/sssd15-06.nl
wget https://www.minlplib.org/nl/sssd15-08.nl
wget https://www.minlplib.org/nl/sssd16-07.nl
wget https://www.minlplib.org/nl/sssd18-06.nl
wget https://www.minlplib.org/nl/sssd18-08.nl
wget https://www.minlplib.org/nl/sssd20-04.nl
wget https://www.minlplib.org/nl/sssd20-08.nl
wget https://www.minlplib.org/nl/sssd22-08.nl
wget https://www.minlplib.org/nl/sssd25-04.nl
wget https://www.minlplib.org/nl/sssd25-08.nl
wget https://www.minlplib.org/nl/st_e14.nl
wget https://www.minlplib.org/nl/st_miqp1.nl
wget https://www.minlplib.org/nl/st_miqp2.nl
wget https://www.minlplib.org/nl/st_miqp3.nl
wget https://www.minlplib.org/nl/st_miqp4.nl
wget https://www.minlplib.org/nl/st_miqp5.nl
wget https://www.minlplib.org/nl/st_test1.nl
wget https://www.minlplib.org/nl/st_test2.nl
wget https://www.minlplib.org/nl/st_test3.nl
wget https://www.minlplib.org/nl/st_test4.nl
wget https://www.minlplib.org/nl/st_test5.nl
wget https://www.minlplib.org/nl/st_test6.nl
wget https://www.minlplib.org/nl/st_test8.nl
wget https://www.minlplib.org/nl/st_testgr1.nl
wget https://www.minlplib.org/nl/st_testgr3.nl
wget https://www.minlplib.org/nl/st_testph4.nl
wget https://www.minlplib.org/nl/stockcycle.nl
wget https://www.minlplib.org/nl/syn05hfsg.nl
wget https://www.minlplib.org/nl/syn05m.nl
wget https://www.minlplib.org/nl/syn05m02hfsg.nl
wget https://www.minlplib.org/nl/syn05m02m.nl
wget https://www.minlplib.org/nl/syn05m03hfsg.nl
wget https://www.minlplib.org/nl/syn05m03m.nl
wget https://www.minlplib.org/nl/syn05m04hfsg.nl
wget https://www.minlplib.org/nl/syn05m04m.nl
wget https://www.minlplib.org/nl/syn10hfsg.nl
wget https://www.minlplib.org/nl/syn10m.nl
wget https://www.minlplib.org/nl/syn10m02hfsg.nl
wget https://www.minlplib.org/nl/syn10m02m.nl
wget https://www.minlplib.org/nl/syn10m03hfsg.nl
wget https://www.minlplib.org/nl/syn10m03m.nl
wget https://www.minlplib.org/nl/syn10m04hfsg.nl
wget https://www.minlplib.org/nl/syn10m04m.nl
wget https://www.minlplib.org/nl/syn15hfsg.nl
wget https://www.minlplib.org/nl/syn15m.nl
wget https://www.minlplib.org/nl/syn15m02hfsg.nl
wget https://www.minlplib.org/nl/syn15m02m.nl
wget https://www.minlplib.org/nl/syn15m03hfsg.nl
wget https://www.minlplib.org/nl/syn15m03m.nl
wget https://www.minlplib.org/nl/syn15m04hfsg.nl
wget https://www.minlplib.org/nl/syn15m04m.nl
wget https://www.minlplib.org/nl/syn20hfsg.nl
wget https://www.minlplib.org/nl/syn20m.nl
wget https://www.minlplib.org/nl/syn20m02hfsg.nl
wget https://www.minlplib.org/nl/syn20m02m.nl
wget https://www.minlplib.org/nl/syn20m03hfsg.nl
wget https://www.minlplib.org/nl/syn20m03m.nl
wget https://www.minlplib.org/nl/syn20m04hfsg.nl
wget https://www.minlplib.org/nl/syn20m04m.nl
wget https://www.minlplib.org/nl/syn30hfsg.nl
wget https://www.minlplib.org/nl/syn30m.nl
wget https://www.minlplib.org/nl/syn30m02hfsg.nl
wget https://www.minlplib.org/nl/syn30m02m.nl
wget https://www.minlplib.org/nl/syn30m03hfsg.nl
wget https://www.minlplib.org/nl/syn30m03m.nl
wget https://www.minlplib.org/nl/syn30m04hfsg.nl
wget https://www.minlplib.org/nl/syn30m04m.nl
wget https://www.minlplib.org/nl/syn40hfsg.nl
wget https://www.minlplib.org/nl/syn40m.nl
wget https://www.minlplib.org/nl/syn40m02hfsg.nl
wget https://www.minlplib.org/nl/syn40m02m.nl
wget https://www.minlplib.org/nl/syn40m03hfsg.nl
wget https://www.minlplib.org/nl/syn40m03m.nl
wget https://www.minlplib.org/nl/syn40m04hfsg.nl
wget https://www.minlplib.org/nl/syn40m04m.nl
wget https://www.minlplib.org/nl/synthes1.nl
wget https://www.minlplib.org/nl/synthes2.nl
wget https://www.minlplib.org/nl/synthes3.nl
wget https://www.minlplib.org/nl/tls12.nl
wget https://www.minlplib.org/nl/tls2.nl
wget https://www.minlplib.org/nl/tls4.nl
wget https://www.minlplib.org/nl/tls5.nl
wget https://www.minlplib.org/nl/tls6.nl
wget https://www.minlplib.org/nl/tls7.nl
wget https://www.minlplib.org/nl/unitcommit1.nl
wget https://www.minlplib.org/nl/unitcommit_200_100_1_mod_8.nl
wget https://www.minlplib.org/nl/unitcommit_200_100_2_mod_8.nl
wget https://www.minlplib.org/nl/unitcommit_50_20_2_mod_8.nl
wget https://www.minlplib.org/nl/watercontamination0202.nl
wget https://www.minlplib.org/nl/watercontamination0202r.nl
wget https://www.minlplib.org/nl/watercontamination0303.nl
wget https://www.minlplib.org/nl/watercontamination0303r.nl
